#ifndef ____PUBLIC_DEFINE_HEADER____
#define ____PUBLIC_DEFINE_HEADER____

enum
{
	WM_MSG_LOGIN_SUCCESS = 0x8000,
	WM_MSG_LOGIN_FAILURE,
	WM_MSG_RTN_ORDER,
	WM_MSG_RTN_TRADE,
	WM_MSG_LOGOUT_SUCCESS,
	WM_MSG_LOGOUT_FAILURE,
	WM_MSG_RSPQRYINSTRUMENT,
	WM_MSG_RSPQRYINSTRUMETNEND,
	WM_MSG_RSPQRYINSTRUMENTMARGINRATE,
	WM_MSG_RSPQRYINSTRUMENTCOMMIRATE,
};

#define  LOG_APP_LEVEL		1
#define  LOG_WARN_LEVEL		2
#define  LOG_ERROR_LEVEL	3
#define  LOG_DEBUG_LEVEL	4

#endif